### ISSUE TITLE
ジャンプできないリソース表現がある

### ISSUE THREAD

**Issue by yuki777** [pj8/vscode-bear-goto#47]
- [x] `#[ResourceParam(uri: 'app://self/user#ulid', param: 'userId')]` #63
- [x] `#[Embed(rel: 'foo', src: 'app://self/foo{?ulid}')]` #63
- [x] `$this->resource->get->uri('app://self/foo/bar-baz')([])` #60 
- [x] `{{= resource('app://self/foo/bar') }}` #58
